### ISSUE TITLE
闪退 

### ISSUE THREAD

**Issue by dysen2014** [warkiz/IndicatorSeekBar#172]
您好，  我在用这个库时  在Android8.0以前，遇到闪退。我是吧indicatorSeekbar放在自定义键盘一起使用，键盘能正常使用，一触碰IndicatorSeekBar就闪退。在android8.0级以上测试过，没问题。

**Comment by warkiz** [comment]
@dysen2014 你好，能提供一些log信息吗？我这边在8.0是可以运行的

**Comment by gitzsl** [comment]
@warkiz 您好，经测试，在vivo和oppo机型 6.0.1系统，会报错，高版本系统上正常，错误信息如下：
E/MessageQueue-JNI: android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ColorViewRootImplHooks$ColorW@522f5a2 is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:635)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
        at android.widget.PopupWindow.invokePopup(PopupWindow.java:1262)
        at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1110)
        at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1069)
        at com.warkiz.widget.Indicator.show(Indicator.java:238)
        at com.warkiz.widget.IndicatorSeekBar.updateIndicator(IndicatorSeekBar.java:1311)
        at com.warkiz.widget.IndicatorSeekBar.refreshSeekBar(IndicatorSeekBar.java:1237)
        at com.warkiz.widget.IndicatorSeekBar.onTouchEvent(IndicatorSeekBar.java:1209)
        at android.view.View.dispatchTouchEvent(View.java:9328)
        at com.warkiz.widget.IndicatorSeekBar.dispatchTouchEvent(IndicatorSeekBar.java:1165)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2207)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2207)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2207)
        at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:1972)
        at android.view.View.dispatchPointerEvent(View.java:9548)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4515)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4313)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3823)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3883)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3842)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3990)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3850)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4047)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3823)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3883)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3842)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3850)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3823)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6239)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6213)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6174)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6346)
        at android.view.ViewRootImpl$ColorWindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7598)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:5769)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
