### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: android.content.res.ColorStateList.getStates

### ISSUE THREAD

**Issue by W-quan** [warkiz/IndicatorSeekBar#74]
```
   UncaughtException detected: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yiwuzhibo/com.yiwuzhibo.MainActivity}: android.view.InflateException: Binary XML file line #119: Error inflating class com.warkiz.widget.IndicatorSeekBar
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2200)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
        at android.app.ActivityThread.access$800(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5052)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #119: Error inflating class com.warkiz.widget.IndicatorSeekBar
        at android.view.LayoutInflater.createView(LayoutInflater.java:623)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
        at com.yiwuzhibo.MainActivity.onCreate(MainActivity.java:177)
        at android.app.Activity.performCreate(Activity.java:5242)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249) 
        at android.app.ActivityThread.access$800(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5052) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at android.view.LayoutInflater.createView(LayoutInflater.java:597)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
        at com.yiwuzhibo.MainActivity.onCreate(MainActivity.java:177) 
        at android.app.Activity.performCreate(Activity.java:5242) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249) 
        at android.app.ActivityThread.access$800(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5052) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.NoSuchMethodError: android.content.res.ColorStateList.getStates
        at com.warkiz.widget.IndicatorSeekBar.initThumbColor(IndicatorSeekBar.java:751)
        at com.warkiz.widget.IndicatorSeekBar.initAttrs(IndicatorSeekBar.java:196)
        at com.warkiz.widget.IndicatorSeekBar.<init>(IndicatorSeekBar.java:147)
        at com.warkiz.widget.IndicatorSeekBar.<init>(IndicatorSeekBar.java:141)
```

红米note1， Android 4.4

**Comment by W-quan** [comment]
一定要使用隐藏API吗？  这样会在定制ROM上有问题

**Comment by W-quan** [comment]
vivo x520L Android 4.4.2  也同样报这个错

**Comment by warkiz** [comment]
@W-quan 大概知道什么问题了，争取下版本改一下

**Comment by W-quan** [comment]
兄弟，能不能 先简单粗暴地  加个 try catch。 明天版本上线，急😂

**Comment by warkiz** [comment]
@W-quan 既然你这么说，我今晚花点时间更正它😂

**Comment by W-quan** [comment]
好感动😭，万分感谢

**Comment by warkiz** [comment]
@W-quan 请使用最新版本试试看，我这里没有4.4的机，测不了。如果ok了麻烦帮忙close一下issue. thanks.

**Comment by W-quan** [comment]
4.4测试没问题了。  看了下实现是改用反射。 Android P 不是就要禁止使用非公开API了吗，我觉得这种实现还是会隐藏问题。

有没有一种使用公开API的实现方式？
