### ISSUE TITLE
custom layout for indicator crash

### ISSUE THREAD

**Issue by Mumot145** [warkiz/IndicatorSeekBar#97]
when setting isb_show_indicator to custom and isb_indicator_content_layout to a png that is supposed to be the indicator background, app crashes.

Error:
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.patrickmumot.eatingdice, PID: 10209
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.patrickmumot.eatingdice/com.patrickmumot.eatingdice.CategoriesActivity}: android.view.InflateException: Binary XML file line #95: Binary XML file line #95: Error inflating class com.warkiz.widget.IndicatorSeekBar
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                   Caused by: android.view.InflateException: Binary XML file line #95: Binary XML file line #95: Error inflating class com.warkiz.widget.IndicatorSeekBar
                   Caused by: android.view.InflateException: Binary XML file line #95: Error inflating class com.warkiz.widget.IndicatorSeekBar
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.newInstance0(Native Method)
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                      at com.patrickmumot.eatingdice.CategoriesActivity.onCreate(CategoriesActivity.java:68)
                      at android.app.Activity.performCreate(Activity.java:6679)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                   Caused by: android.content.res.Resources$NotFoundException: File res/drawable/indicator.png from xml type layout resource ID #0x7f0700b3
                      at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:990)
                      at android.content.res.Resources.loadXmlResourceParser(Resources.java:2103)
                      at android.content.res.Resources.getLayout(Resources.java:1115)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:424)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
E/AndroidRuntime:     at android.view.View.inflate(View.java:21010)
                      at com.warkiz.widget.IndicatorSeekBar.initAttrs(IndicatorSeekBar.java:224)
                      at com.warkiz.widget.IndicatorSeekBar.<init>(IndicatorSeekBar.java:150)
                      at com.warkiz.widget.IndicatorSeekBar.<init>(IndicatorSeekBar.java:144)
                      	... 31 more
                   Caused by: java.io.FileNotFoundException: Corrupt XML binary file
                      at android.content.res.AssetManager.openXmlAssetNative(Native Method)
                      at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:519)
                      at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:975)
                      	... 39 more

**Comment by abhishektiwarijr** [comment]
What's the solution for this?

**Comment by abhishektiwarijr** [comment]
Thank you @warkiz 
Tried on API Level 19 or below???

**Comment by searchy2** [comment]
@Mumot145 Can you post your layout that is crashing? Everything works for me on API 21.

**Comment by warkiz** [comment]
No response. Close.
